common:
  msg_source: 1                         # 0: not use Lidar
                                        # 1: packet message comes from online Lidar
                                        # 2: packet message comes from ROS or ROS2
                                        # 3: packet message comes from Pcap file
  send_packet_ros: false                # true: Send packets through ROS or ROS2(Used to record packet)
  send_point_cloud_ros: true            # true: Send point cloud through ROS or ROS2
lidar:
  # 前顶lidar
  - driver:
      lidar_type: RSM1             #  LiDAR type - RS16, RS32, RSBP, RSAIRY, RSHELIOS, RSHELIOS_16P, RS128, RS80, RS48, RSP128, RSP80, RSP48, 
                                   #               RSM1, RSM1_JUMBO, RSM2, RSM3, RSE1, RSMX.
                                   
      msop_port: 6699              #  Msop port of lidar
      difop_port: 7788             #  Difop port of lidar
      imu_port: 0                  #  IMU port of lidar(only for RSAIRY, RSE1), 0 means no imu.
                                   #  If you want to use IMU, please first set ENABLE_IMU_DATA_PARSE to ON in CMakeLists.txt 
      user_layer_bytes: 0          #  Bytes of user layer. thers is no user layer if it is 0         
      tail_layer_bytes: 0          #  Bytes of tail layer. thers is no tail layer if it is 0

      min_distance: 0.2           #  Minimum distance of point cloud
      max_distance: 200            #  Maximum distance of point cloud
      use_lidar_clock: true        #  true--Use the lidar clock as the message timestamp
                                   #  false-- Use the system clock as the timestamp
      dense_points: true           #  true: discard NAN points; false: reserve NAN points
      
      ts_first_point: true         #  true: time-stamp point cloud with the first point; false: with the last point;   
                                   #  these parameters are used from mechanical lidar

      start_angle: 0               #  Start angle of point cloud
      end_angle: 360               #  End angle of point cloud

                                   #  When msg_source is 3, the following parameters will be used
      pcap_repeat: true            #  true: The pcap bag will repeat play   
      pcap_rate: 1.0               #  Rate to read the pcap file
      pcap_path: /home/robosense/lidar.pcap #The path of pcap file

    ros:
      ros_frame_id: lidar_ft_base_link                           #Frame id of packet message and point cloud message
      ros_recv_packet_topic: /sensing/lidar/front_top/packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /sensing/lidar/front_top/packets          #Topic used to send lidar packets through ROS
      ros_send_imu_data_topic: /sensing/lidar/front_top/imu_data         #Topic used to send imu data through ROS
      ros_send_point_cloud_topic: /sensing/lidar/front_top/points      #Topic used to send point cloud through ROS
      ros_queue_length: 100                            #Topic QoS history depth
  
  # 后顶lidar
  - driver:
      lidar_type: RSM1            
      msop_port: 6688              
      difop_port: 7777            
      imu_port: 0                  
                                   
      user_layer_bytes: 0                  
      tail_layer_bytes: 0          
      min_distance: 0.2           
      max_distance: 200            
      use_lidar_clock: true        
      dense_points: true           
      ts_first_point: true            
      start_angle: 0               
      end_angle: 360               
      pcap_repeat: true              
      pcap_rate: 1.0               
      pcap_path: /home/robosense/lidar.pcap 

    ros:
      ros_frame_id: lidar_rt_base_link                           
      ros_recv_packet_topic: /sensing/lidar/rear_top/packets          
      ros_send_packet_topic: /sensing/lidar/rear_top/packets          
      ros_send_imu_data_topic: /sensing/lidar/rear_top/imu_data         
      ros_send_point_cloud_topic: /sensing/lidar/rear_top/points      
      ros_queue_length: 100  
  
  # 前左lidar
  - driver:
      lidar_type: RSAIRY          
      msop_port: 6677              
      difop_port: 7766            
      imu_port: 0    

      user_layer_bytes: 0                
      tail_layer_bytes: 0          
      min_distance: 0.2        
      max_distance: 40            
      use_lidar_clock: true        
      dense_points: true           
      ts_first_point: true            
      start_angle: -110               
      end_angle: 150               
      pcap_repeat: true              
      pcap_rate: 1.0               
      pcap_path: /home/robosense/lidar.pcap 
      split_frame_mode: 1
      split_angle: 180.0

    ros:
      ros_frame_id: lidar_fl_base_link                           
      ros_recv_packet_topic: /sensing/lidar/front_left/packets          
      ros_send_packet_topic: /sensing/lidar/front_left/packets          
      ros_send_imu_data_topic: /sensing/lidar/front_left/imu_data         
      ros_send_point_cloud_topic: /sensing/lidar/front_left/points      
      ros_queue_length: 100  

  # 前右lidar
  - driver:
      lidar_type: RSAIRY          
      msop_port: 6666              
      difop_port: 7755             
      imu_port: 0                  
                                   
      user_layer_bytes: 0                  
      tail_layer_bytes: 0          
      min_distance: 10.0          
      max_distance: 40            
      use_lidar_clock: true        
      dense_points: true           
      ts_first_point: true            
      start_angle: -110               
      end_angle: 150               
      pcap_repeat: true              
      pcap_rate: 1.0               
      pcap_path: /home/robosense/lidar.pcap 
      split_frame_mode: 1
      split_angle: 180.0

    ros:
      ros_frame_id: lidar_fr_base_link                           
      ros_recv_packet_topic: /sensing/lidar/front_right/packets          
      ros_send_packet_topic: /sensing/lidar/front_right/packets          
      ros_send_imu_data_topic: /sensing/lidar/front_right/imu_data         
      ros_send_point_cloud_topic: /sensing/lidar/front_right/points      
      ros_queue_length: 100  
  
  # 后中lidar
  - driver:
      lidar_type: RSE1            
      msop_port: 6655            
      difop_port: 7744            
      imu_port: 0                  
                                   
      user_layer_bytes: 0                  
      tail_layer_bytes: 0          
      min_distance: 15.0           
      max_distance: 200            
      use_lidar_clock: true        
      dense_points: true           
      ts_first_point: true            
      start_angle: 0               
      end_angle: 360               
      pcap_repeat: true              
      pcap_rate: 1.0               
      pcap_path: /home/robosense/lidar.pcap 

    ros:
      ros_frame_id: lidar_rear_base_link                           
      ros_recv_packet_topic: /sensing/lidar/rear_center/packets          
      ros_send_packet_topic: /sensing/lidar/rear_center/packets          
      ros_send_imu_data_topic: /sensing/lidar/rear_center/imu_data         
      ros_send_point_cloud_topic: /sensing/lidar/rear_center/points      
      ros_queue_length: 100  